apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: fpm
  name: fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fpm
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/pim: "true"
        io.kompose.service: fpm
    spec:
      containers:
      - args:
        - php-fpm
        - -F
        env:
        - name: APP_ENV
          value: prod
        - name: BEHAT_SCREENSHOT_PATH
          value: /srv/pim/var/tests/screenshots
        - name: BEHAT_TMPDIR
          value: /srv/pim/var/cache/tmp
        - name: BLACKFIRE_CLIENT_ID
          value: client_id
        - name: BLACKFIRE_CLIENT_TOKEN
          value: client_token
        - name: PHP_IDE_CONFIG
          value: serverName=pim-docker-web
        - name: XDEBUG_CONFIG
          value: remote_host=172.17.0.1
        - name: XDEBUG_ENABLED
          value: "0"
        image: akeneo/pim-php-dev:master
        imagePullPolicy: ""
        name: fpm
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts:
        - mountPath: /srv/pim
          name: fpm-claim0
        workingDir: /srv/pim
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: fpm-claim0
        persistentVolumeClaim:
          claimName: fpm-claim0
status: {}
